### ISSUE TITLE
컨테이너 생성&삭제&실행 기능 수정

### ISSUE THREAD

**Issue by cipp00h** [cipp00h/SSAP-IDE-BackEnd#19]
## 작업 사항

> AWS에 EB에 배포 후, 컨테이너 생성 API 테스트 결과 이미지 pull부터 진행이 안 되는 문제가 있어 실제 이미지를 pull하고
컨테이너 생성하는 로직은 주석 처리하고, DB에 컨테이너 정보만 넣고, 삭제할 수 있도록 수정.

## To-do
- [x] 기존 DockerHub에서 이미지를 내려받는 로직 주석 처리
- [x] createContainer 컨트롤러에 @Vaild 추가
- [x] JpaRepository 엔티티 타입 수정(Long -> String)
- [x] DockerService.java의 createContainer 기존 메서드 주석 처리 후, 메서드 재생성 (createContainer 메서드 실행 시, UUID값을 생성하여 반환하도록 구현)
- [x] DockerService.java의 deleteContainer, runContainer 메서드 재생성
## 기타사항

> 기타 사항을 작성해주세요
